config/routes.rb
Rails.application.routes.draw do
  resources :places
  
  # match "/places/:id/" => "places#show", via: [:get, :post]


  root 'places#index'
end

app/models/place.rb
class Place < ActiveRecord::Base
	geocoded_by :name   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates	

	def iso3
		return Country.find_country_by_name(self.name).alpha3
	end
	
	def iso2
		return Country.find_country_by_name(self.name).alpha2
	end
	
	def rainData
		return @rainInfo = HTTParty.get("http://climatedataapi.worldbank.org/climateweb/rest/v1/country/mavg/pr/1980/1999/" + self.iso3.to_s)
	end		

	def tempData
		return @tempInfo = HTTParty.get("http://climatedataapi.worldbank.org/climateweb/rest/v1/country/mavg/tas/1980/1999/" + self.iso3.to_s)
	end		

	def capCity
		c = HTTParty.get("http://api.worldbank.org/countries/" + self.iso3.to_s + "/?format=json")
		return @capCity = c[1][0]['capitalCity']
	end

	def countryGeo
		return @co = GeoNamesAPI::Country.find(self.iso2)
	end

	def population
		@pop = self.countryGeo
		return @p = @pop.population
	end

	def currWeather
		lon = self.longitude
		lat = self.latitude
		getLoc = GeoNamesAPI::Country.find(self.iso2)

		north = getLoc.north.to_s
		south = getLoc.south.to_s
		east = getLoc.east.to_s
		west = getLoc.west.to_s
		@currWeather = HTTParty.get("http://api.geonames.org/weatherJSON?north="+north+"&south="+south+"&east="+east+"&west="+west+"&username=hathbanger")
		return @currWeather['weatherObservations']
	end


	def temp
		@temp = self.currWeather.first['temperature']
		
		return @t = (@temp.to_i * 9/5) + 32
	end

	def dew
		@dew = self.currWeather.first['dewPoint']
		
		return d = (@dew.to_i * 9/5) + 32
	end

	def humidity
		@hum = self.currWeather.first['humidity']
		
	end

	def windDir
		@windDirection = self.currWeather.first['windDirection']
		
	end

	def windSpeed
		@windSpeed = self.currWeather.first['windSpeed']
		
	end


	def forcastAndConditions
		@fnc 
		return @fnc
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
    @place = Place.first
  end

  # GET /places/1
  # GET /places/1.json
  def show

    # @place = Place.find(params[:name])

    iso2 = @place.iso2.downcase
    gon.place = @place
    gon.iso2 = iso2


    @res = @place.forcastAndConditions
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WrldAPP</title>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css' %>

  <%= include_gon(:init => true) %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/queue-async/1.0.7/queue.min.js' %>  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdn.rawgit.com/markmarkoh/datamaps/master/dist/datamaps.world.min.js' %>  
</head>
<body>

<%= yield %>
</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div id="map"></div>



<div id="chart"></div>


<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>


<script type="text/javascript">
  
  $(document).ready(function(){
    var w = $(window).width();

      var width = w,
    height = 600,
    sens = 0.25,
    focused;

    //Setting projection

    var projection = d3.geo.orthographic()
    .scale(245)
    .rotate([0, 0])
    .translate([width / 2, height / 2])
    .clipAngle(90);

    var path = d3.geo.path()
    .projection(projection);

    //SVG container

    var svg = d3.select("#map").append("svg")
    .attr("width", width)
    .attr("height", height);

    //Adding water

    svg.append("path")
    .datum({type: "Sphere"})
    .attr("class", "water")
    .attr("d", path);

    var countryTooltip = d3.select("#map").append("div").attr("class", "countryTooltip"),
    countryList = d3.select("#map").append("select").attr("name", "countries").attr("id", "countrySelect");



    queue()
    .defer(d3.json, "/world-110m.json")
    .defer(d3.tsv, "/world-110m-country-names.tsv")
    .await(ready);

    //Main function

    function ready(error, world, countryData) {

      var countryById = {},
      countries = topojson.feature(world, world.objects.countries).features;

      //Adding countries to select

      countryData.forEach(function(d) {
        countryById[d.id] = d.name;
        option = countryList.append("option");
        option.text(d.name);
        option.property("value", d.id);
      });

      //Drawing countries on the globe

      var world = svg.selectAll("path.land")
      .data(countries)
      .enter().append("path")
      .attr("class", "land")
      .attr("d", path)

      //Drag event

      .call(d3.behavior.drag()
        .origin(function() { var r = projection.rotate(); return {x: r[0] / sens, y: -r[1] / sens}; })
        .on("drag", function() {
          var rotate = projection.rotate();
          projection.rotate([d3.event.x * sens, -d3.event.y * sens, rotate[2]]);
          svg.selectAll("path.land").attr("d", path);
          svg.selectAll(".focused").classed("focused", focused = false);
        }))

      //Mouse events

      .on("mouseover", function(d) {
        countryTooltip.text(countryById[d.id])
        .style("left", (d3.event.pageX + 7) + "px")
        .style("top", (d3.event.pageY - 15) + "px")
        .style("display", "block")
        .style("opacity", 1);
      })
      .on("mouseout", function(d) {
        countryTooltip.style("opacity", 0)
        .style("display", "none");
      })
      .on("mousemove", function(d) {
        countryTooltip.style("left", (d3.event.pageX + 7) + "px")
        .style("top", (d3.event.pageY - 15) + "px");
      });

      //Country focus on option select

      d3.select("select").on("change", function() {
        var rotate = projection.rotate(),
        focusedCountry = country(countries, this),
        p = d3.geo.centroid(focusedCountry);

        svg.selectAll(".focused").classed("focused", focused = false);

      //Globe rotating

      (function transition() {
        d3.transition()
        .duration(2500)
        .tween("rotate", function() {
          var r = d3.interpolate(projection.rotate(), [-p[0], -p[1]]);
          return function(t) {
            projection.rotate(r(t));
            svg.selectAll("path").attr("d", path)
            .classed("focused", function(d, i) { return d.id == focusedCountry.id ? focused = d : false; });
          };
        })
        })();
      });

      function country(cnt, sel) { 
        for(var i = 0, l = cnt.length; i < l; i++) {
          if(cnt[i].id == sel.value) {return cnt[i];}
        }
      };

    };

  });  

</script>



<script type="text/javascript">
$(document).ready(function(){
    var chart = c3.generate({
        data: {
            x: 'Year',
          url: '/csv/global_emission.csv',
          type: 'line'
        },
        axis: {
            // x: {
            //     type: 'timeseries',
            //     // if true, treat x value as localtime (Default)
            //     // if false, convert to UTC internally
            //     localtime: false,
            //     tick: {
            //         format: '%Y'
            //     }
            // }
        }
    });

console.log($('#countrySelect option'))


})


</script>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<div class="station">
  <img class="webcam1"></img>
</div>

<div id="container" style="position: relative; width: 500px; height: 600px;"></div>

<p id="notice"><%= notice %></p>

<div class="chartHolder" id="rainChart">
</div>

<div class="chartHolder" id="tempChart">
  
</div>

<p>
<h1><strong><span class="placeName"><%= @place.name %></span></strong></h1><br>


<h1>

</h1>  
<div class="f32">
    <div class="flag selected" data-cc=<%= @place.iso2 %> data-country_name=<%= @place.name %> data-locale=<%= @place.iso2 %> title=<%= @place.name %>>&nbsp;</div>
</div>

<h2>  
    Capital City: <div class="capitalCity"><%= @place.capCity %></div><br>
</h2>
  	<div class="population"> 
      <h3>Population: <span>  <%= @place.population %></span></h3>
    </div>
  Temperature: <%= @place.temp %><br>
  <div class="iso2">
    Iso2: <span><%= @place.iso2 %></span><br>
  </div>
  <div class="iso3">
    Iso3: <span><%= @place.iso3 %></span><br>
  </div>
	Humidity: <%= @place.humidity %><br>
	Dewpoint: <%= @place.dew %><br>
	Wind Speed: <%= @place.windSpeed %><br>
	Wind Direction: <%= @place.windDir %><br>

<div>
 <%= @res %>
</div>
  <% @place.currWeather.each do |x| %>



  <div class="stationInfo" id=<%= x['stationName'].downcase %>>
  <strong>
    <div class="stationName"><%= x['stationName'] %></div>:
  </strong>  
  Latitude: <div class="latitude"><%= x['lat'] %></div>, Longitude: <div class="longitude"><%= x['lng'] %></div>,  
  Clouds: <%= x['clouds'] %>, 
  Temperature: <%= x['temperature'] %>, 
  Humidity: <%= x['humidity'] %>, 
  Dewpoint: <%= x['dewPoint'] %>,  
  Wind Direction: <%= x['windDirection'] %>,  
  Wind Speed: <%= x['windSpeed'] %>
    </div>
  <% end %> 

    <br>
    <br>
    <br>
    <br>

  <% @place.forcastAndConditions do |x| %>
    <%= x  %>
    <br>
    <br>
  <% end %>
  <br>
      <div class="longitude"> 
      <h3>longitude: <span>  <%= @place.longitude %><br></span></h3>
    </div>
      <div class="latitude"> 
      <h3>latitude: <span>  <%= @place.latitude %><br></span></h3>
    </div>
  	



    <% @place.rainData.each do |x| %>
      <span class="rainMonth"><%= x['monthVals'] %></span>
    <% end %>
    <% @place.tempData.each do |x| %>
      <span class="tempMonth"><%= x['monthVals'] %></span>
    <% end %> 
</p>

<div id="chart"></div>
<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

<script type="text/javascript">
$(document).ready(function(){	



  var population = $('.population span').text();
  var iso2 = $('body .iso2 span').text().toLowerCase();
  var iso3 = $('body .iso3 span').text();
  console.log(population);

  var lon = $('.longitude span').text();
  var lat = $('.latitude span').text();
  var place = $(' .placeName').text();


	$('.f32 .flag').addClass(iso2)
console.log(lon)
var chart = c3.generate({
    data: {
        // iris data from R
        columns: [
            ['Population', population],
            ['Global Population', 7378469780],
        ],
        type : 'pie',
        onclick: function (d, i) { console.log("onclick", d, i); },
        onmouseover: function (d, i) { console.log("onmouseover", d, i); },
        onmouseout: function (d, i) { console.log("onmouseout", d, i); }
    }
});	



function addArr(data, target){

  console.log(target.selector)
  var rainH = data
  var rainArr = [];
  var rainTemp = [];


  for(var k = 0; k < rainH.size(); k++){
    var item = rainH[k].innerHTML;
    rainArr.push($.parseJSON(item));
  }

  for(var k = 0; k < rainH.size(); k++){
    var item = rainH[k].innerHTML;
    var rainArr = [];
    for(var e = 0; e < rainH.size(); e++){
      rainArr.push($.parseJSON(item)[e]);
    }
    rainTemp.push(['data'+k, rainArr[1],rainArr[2],rainArr[3],rainArr[4],rainArr[5],rainArr[6],rainArr[7],rainArr[8],rainArr[9],rainArr[10],rainArr[11]]);
  }

  var wid = $(document).width();
  target.width(wid/2)
  var chart2 = c3.generate({
      bindto: target.selector,
      data: {
        columns: [
          rainTemp[1]
        ],
        type: 'spline',
        axes: {
          data2: 'y2' // ADD
        }
      },
      axis: {
        y2: {
          show: true // ADD
        }
      }
    });

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[2]
          ]
      });
  }, 500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[3],
          ]
      });
  }, 1500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[4],
          ]
      });
  }, 2500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[5],
          ]
      });
  }, 3500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[6],
          ]
      });
  }, 4500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[7],
          ]
      });
  }, 5500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[8],
          ]
      });
  }, 6500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[9],
          ]
      });
  }, 7500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[10],
          ]
      });
  }, 8500);

  setTimeout(function () {
      chart2.load({
          columns: [
              rainTemp[12],
          ]
      });
  }, 9500);

  setTimeout(function () {
      chart2.unload({
          ids: 'data1'
      });
  }, 10500);


}

var w = $(document).width();

$('#container').width(w);

    var map = new Datamap({
        element: document.getElementById('container'),
        scope: 'world',
        fills: {
            HIGH: '#afafaf',
            LOW: '#123456',
            MEDIUM: 'blue',
            UNKNOWN: 'rgb(0,0,0)',
            defaultFill: 'green'
        },
        data: {
            IRL: {
                fillKey: 'LOW',
                numberOfThings: 2002
            },
            USA: {
                fillKey: 'MEDIUM',
                numberOfThings: 10381
            }
        },
        setProjection: function(element) {
            var projection = d3.geo.mercator()
              .center([lon, lat])
              .rotate([4.4, 0])
              .scale(1200)
              .translate([element.offsetWidth / 2, element.offsetHeight / 2]);
            var path = d3.geo.path()
              .projection(projection);
            
            return {path: path, projection: projection};
          },
        geographyConfig: {
            popupTemplate: function(geo, data) {
                return ['<div class="hoverinfo"><strong>',
                        'Number of things in ' + geo.properties.name,
                        ': ' + data.numberOfThings,
                        '</strong></div>'].join('');
            }
        }

   }); 

console.log($('.stationInfo')[0].innerText);
var stations = $('.stationInfo');


function stationLoop(){
  for(var j = 0; j < stations.size(); j++){
    var station = stations[j];
    console.log(station)
    map.bubbles([
      {
        name: station.innerText.stationName,
        radius: 7,
        yeild: 15000,
        country: iso3,
        significance: 'First dry fusion fuel "staged" thermonuclear weapon; a serious nuclear fallout accident occurred',
        fillKey: iso3,
        date: '1954-03-01',
        latitude: station.innerText.Latitude,
        longitude: station.innerText.Lontitude
      }
    ])
  }

}

stationLoop()


// map.bubbles([
//   {
//     name: 'Castle Bravo',
//     radius: 7,
//     yeild: 15000,
//     country: iso3,
//     significance: 'First dry fusion fuel "staged" thermonuclear weapon; a serious nuclear fallout accident occurred',
//     fillKey: 'USA',
//     date: '1954-03-01',
//     latitude: lat,
//     longitude: lon
//   }
// ])

       
  console.log(lon)

var r = $('.rainMonth');
var c = $('#rainChart');
var tm = $('.tempMonth');
var t = $('#tempChart');

addArr(r, c);
addArr(tm, t);

// var arrRain = ['data', rainArr[1],rainArr[2],rainArr[3],rainArr[4],rainArr[5],rainArr[6],rainArr[7],rainArr[8],rainArr[9],rainArr[10],rainArr[11],rainArr[12],rainArr[13]];

});

  var place = $(' .placeName').text();
  var capCity = $(' .capitalCity').text();
  console.log(place);
  console.log(capCity);



$.ajax({
  url: "http://api.wunderground.com/api/40deb120c22e57b2/webcams/q/"+ place +"/"+ capCity +".json",
  beforeSend: function( xhr ) {
    xhr.overrideMimeType( "text/plain; charset=x-user-defined" );
    
  }
})
  .done(function( data ) {
    if ( console && console.log ) {
      var extractedData = $.parseJSON(data).webcams[0];
      console.log(extractedData);
      
      if(extractedData != null){
        var img1 = extractedData.CURRENTIMAGEURL;
        console.log(img1);
        $('.webcam1').attr('src', img1)
      }
    }
  });



</script>